[2020-07-31 05:53:35,474] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: DAG_jira.load_issues 2020-07-30T21:29:00+00:00 [queued]>
[2020-07-31 05:53:35,514] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: DAG_jira.load_issues 2020-07-30T21:29:00+00:00 [queued]>
[2020-07-31 05:53:35,515] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-07-31 05:53:35,515] {taskinstance.py:867} INFO - Starting attempt 1 of 1
[2020-07-31 05:53:35,515] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-07-31 05:53:35,549] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): load_issues> on 2020-07-30T21:29:00+00:00
[2020-07-31 05:53:35,569] {standard_task_runner.py:53} INFO - Started process 7506 to run task
[2020-07-31 05:53:35,704] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: DAG_jira.load_issues 2020-07-30T21:29:00+00:00 [running]> 02f6ef7ded4c
[2020-07-31 05:53:35,760] {taskinstance.py:1128} ERROR - [Errno 2] No such file or directory: 'dag_data/dag_jira_data.json'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/KafkaPOC/dags/jira_datapipeline.py", line 68, in load_issues
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'dag_data/dag_jira_data.json'
[2020-07-31 05:53:35,764] {taskinstance.py:1185} INFO - Marking task as FAILED.dag_id=DAG_jira, task_id=load_issues, execution_date=20200730T212900, start_date=20200731T055335, end_date=20200731T055335
[2020-07-31 05:53:45,439] {logging_mixin.py:112} INFO - [2020-07-31 05:53:45,438] {local_task_job.py:103} INFO - Task exited with return code 1
